# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/21141/Desktop/AD9361_QPSK/prj/AD9361_QPSK.srcs/sources_1/ip/ipath_generator/ipath_generator.xci
# IP: The module: 'ipath_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/21141/Desktop/AD9361_QPSK/prj/AD9361_QPSK.gen/sources_1/ip/ipath_generator/ipath_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ipath_generator'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/21141/Desktop/AD9361_QPSK/prj/AD9361_QPSK.srcs/sources_1/ip/ipath_generator/ipath_generator.xci
# IP: The module: 'ipath_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/21141/Desktop/AD9361_QPSK/prj/AD9361_QPSK.gen/sources_1/ip/ipath_generator/ipath_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ipath_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
